app = "blazed-deals-redis"
primary_region = 'iad'

[mounts]
  destination = "/data"
  source = "blazed_deals_redis"

[metrics]
  port = 9091
  path = "/metrics"

[build]
  image = "flyio/redis:6.2.6"
  
[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'

# Uncomment these lines for public internet access to Redis on port 10000
#
# [[services]]
# internal_port = 6379
# protocol      = "tcp"

#   [[services.ports]]
#   port     = "10000"

#   [[services.tcp_checks]]
#   interval = 10000
#   timeout  = 2000
